apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-a
  name: deployment-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-a
    spec:
      containers:
      - image: eficodeacademy/devopsacademya:latest
        name: devopsacademya
        resources: {}
status: {}
