apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-frontend
  name: deployment-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-frontend
  template:
    metadata:
      labels:
        app: deployment-frontend
    spec:
      containers:
      - image: dock231/frontend:latest
        name: simple-fortune-cookie-frontend
        ports: 
        - containerPort: 8080
        env:
        - name: BACKEND_DNS
          value: service-backend
        - name: BACKEND_PORT
          value: "9000"

