apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: dock231/frontend:latest
        name: simple-fortune-cookie-frontend
        env:
        - name: BACKEND_DNS
          value: ./deployment-backend.yaml
        - name: BACKEND_PORT
          value: 9000

