apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-db
  name: service-db
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: deployment-db
  type: ClusterIP
status:
  loadBalancer: {}